#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Open aquarium door (magnetic lock via intercom)
"$DIR/mqtt-send" -t 'bus/devices/aquarium.door/lock/set' -m '1'

# Power-up solenoid in red door lock mechanism
"$DIR/mqtt-send" -t 'bus/devices/portal.reddoor/lock/set' -m '1'

# KOZHANYE MESHKI need some time to move thru the doors
sleep 10

# Lock aquarium door
"$DIR/mqtt-send" -t 'bus/devices/aquarium.door/lock/set' -m '0'

# Red door should be already powered off by another script
